# Generated by Django 6.1.2 on 2026-10-07 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: AccuStandard, MERCK, Thermo Scientific, Zeiss, Biobase, Electrolux', max_length=100, unique=True, verbose_name='Nombre de la Marca / Fabricante')),
                ('pais_origen', models.CharField(blank=True, max_length=100, verbose_name='País de Origen')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Notas')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas y Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Microscopio con adaptación Axiocam, Espectofotometro UV Visible, Liofilizador', max_length=200, verbose_name='Nombre del Equipo')),
                ('cantidad', models.IntegerField(default=1, help_text='Número de unidades (ej: 4 neveras, 1 espectrofotómetro)', verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('Usado', 'Usado'), ('Sin uso', 'Sin uso'), ('Operativo', 'Operativo'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Usado', max_length=30, verbose_name='Estado')),
                ('fotografia', models.ImageField(blank=True, help_text='Foto real para identificar visualmente el equipo en el laboratorio', null=True, upload_to='equipos/', verbose_name='Fotografía del Equipo')),
                ('placa_udc', models.CharField(blank=True, help_text='Código institucional de activo si aplica', max_length=50, verbose_name='Placa Activo UDC')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('ubicacion_interna', models.CharField(blank=True, help_text='Ej: Mesón central, Zona de espectrometría', max_length=150, verbose_name='Ubicación en el Espacio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='sedes.espacio', verbose_name='Espacio / Laboratorio')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.marca', verbose_name='Marca / Fabricante')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos de Laboratorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MUESTREO_SEDIMENTOS', 'Material de Muestreo (Sedimentos)'), ('MUESTREO_PECES', 'Material de Muestreo (Peces)'), ('VIDRIO', 'Material de Vidrio'), ('LIMPIEZA', 'Material de Limpieza'), ('BIOMEDICO', 'Material Muestreo Humano'), ('VARIOS', 'Materiales Varios')], max_length=30, verbose_name='Categoría / Tipo de Material')),
                ('nombre', models.CharField(help_text='Ej: Tubos tapa lila, Balon fondo redondo (1000mL), Algodón, Caba de icopor', max_length=200, verbose_name='Nombre del Artículo / Insumo')),
                ('cantidad', models.CharField(help_text='Ej: 910 unidades, 7 cajas x100, 1/2 Bolsa, 44, 1', max_length=80, verbose_name='Cantidad / Presentación')),
                ('estado', models.CharField(choices=[('Sin uso', 'Sin uso'), ('Usado', 'Usado'), ('En uso', 'En uso'), ('No hay', 'No hay / Agotado')], default='Sin uso', max_length=30, verbose_name='Estado')),
                ('ubicacion_interna', models.CharField(blank=True, help_text='Ej: Estante de vidrio, Gaveta 3, Módulo de bioseguridad', max_length=150, verbose_name='Ubicación Interna')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='sedes.espacio', verbose_name='Espacio / Laboratorio')),
            ],
            options={
                'verbose_name': 'Material / Insumo',
                'verbose_name_plural': 'Materiales e Insumos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALIDA_CONSUMO', 'Salida / Consumo'), ('INGRESO_COMPRA', 'Ingreso / Compra'), ('TRASLADO', 'Traslado entre Sedes / Espacios'), ('ROTURA_BAJA', 'Baja por Rotura / Deterioro')], default='SALIDA_CONSUMO', max_length=30, verbose_name='Tipo de Movimiento')),
                ('item_descripcion', models.CharField(help_text='Nombre del ítem movido', max_length=255, verbose_name='Artículo / Reactivo / Material')),
                ('cantidad', models.CharField(help_text='Ej: 50 mL, 2 cajas, 1 unidad', max_length=50, verbose_name='Cantidad Movida')),
                ('proyecto', models.CharField(blank=True, help_text='Proyecto MinCiencias o tesis para el cual se utilizó', max_length=150, verbose_name='Proyecto / Tesis / Semillero')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas / Justificación')),
                ('espacio_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='sedes.espacio', verbose_name='Espacio Destino')),
                ('espacio_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='sedes.espacio', verbose_name='Espacio Origen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTANDAR', 'Estándar'), ('BUFFER', 'Buffer'), ('REACTIVO', 'Reactivo')], default='REACTIVO', max_length=20, verbose_name='Tipo (Estándar/Buffer/Reactivo)')),
                ('nombre', models.CharField(help_text='Ej: Dichloromethane, Pyrene, Ácido sulfúrico 95-97%, Buffer pH 7.00', max_length=200, verbose_name='Nombre / Sustancia')),
                ('presentacion', models.CharField(blank=True, help_text='Ej: Líquido, Sólido', max_length=100, verbose_name='Presentación')),
                ('lote', models.CharField(blank=True, help_text='Número de lote (opcional; en Buffers suele no tener)', max_length=100, verbose_name='Lote')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Z-014J, Orion 910110, 1007312500', max_length=100, verbose_name='Referencia / Catálogo')),
                ('fecha_expedicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición / Vencimiento')),
                ('cantidad', models.CharField(blank=True, help_text='Ej: 2 mL, 10mg, 475 mL, 2.5L, 4L', max_length=50, verbose_name='Cantidad / Contenido')),
                ('unidades', models.CharField(default='1', help_text='Número de frascos físicos (ej: 1, 2)', max_length=20, verbose_name='Unidades (Frascos)')),
                ('estado_uso', models.CharField(choices=[('Sin uso', 'Sin uso'), ('Usado', 'Usado'), ('En uso', 'En uso'), ('Agotado', 'Agotado')], default='Sin uso', max_length=30, verbose_name='Estado de Uso')),
                ('clasificacion', models.CharField(blank=True, help_text='Ej: ACIDO, SAL, SOLVENTE ORGANICO', max_length=100, verbose_name='Clasificación Química')),
                ('ubicacion_interna', models.CharField(blank=True, help_text='Ej: Nevera 1, Congelador -20°C, Gabinete de ácidos', max_length=150, verbose_name='Ubicación Interna')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivos', to='sedes.espacio', verbose_name='Espacio / Laboratorio')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivos', to='inventario.marca', verbose_name='Marca / Fabricante')),
            ],
            options={
                'verbose_name': 'Reactivo / Estándar',
                'verbose_name_plural': 'Reactivos, Estándares y Buffers',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
