# Generated by Django 6.1.2 on 2026-10-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_marca_options_remove_marca_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Foto de referencia rápida (también puedes agregar múltiples fotos en la galería abajo)', null=True, upload_to='equipos/', verbose_name='Fotografía Principal'),
        ),
        migrations.CreateModel(
            name='ImagenEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='equipos/galeria/', verbose_name='Fotografía')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Vista frontal, Placa de serie, Accesorios, Conexión trasera', max_length=150, verbose_name='Descripción / Epígrafe')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es la foto principal de portada?')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Fotografía del Equipo',
                'verbose_name_plural': 'Galería de Fotografías del Equipo',
                'ordering': ['-es_principal', '-fecha_subida'],
            },
        ),
    ]
