# Generated by Django 6.1.2 on 2026-10-07 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: CREAD, Zaragocilla, San Agustín, Piedra de Bolívar', max_length=150, unique=True, verbose_name='Nombre de la Sede')),
                ('ciudad', models.CharField(default='Cartagena de Indias', max_length=100, verbose_name='Ciudad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Ubicación')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Laboratorio 109, Laboratorio de Toxicología, Oficina de Estudiantes', max_length=150, verbose_name='Nombre del Espacio')),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('otro', 'Otro')], default='laboratorio', max_length=20, verbose_name='Tipo de Espacio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Custodio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='sedes.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['sede', 'nombre'],
                'unique_together': {('sede', 'nombre')},
            },
        ),
    ]
